"""
Golden-equivalence baseline for the current FinServ lambda_handler.

Task 1 — FinServ Shared-Inventory Refactor (FU-3)
Requirements: REQ-5.1, REQ-5.3, REQ-5.6

Strategy
--------
Build a reusable single-page "account state" fixture that covers PASS, FAIL,
N/A (status="N/A"), and ADVISORY paths across the inventory-consuming checks:

  * Lambda functions (FS-09, 52, 55, 58, 67, 69)
  * Guardrails + detail (FS-27a, 28, 36, 38, 45, 47, 50, 51, 59)
  * Knowledge Bases + data sources + detail (FS-24, 31, 33, 48, 61, 65)
  * S3 buckets (FS-21, 46)
  * WAFv2 Web ACLs + detail (FS-01, 53, 56, 68)

Constraints (REQ-5.3): ≤100 Web ACLs and ≤1 page of buckets so the fixture
remains single-page comparable after the pagination fix in Task 9.

The frozen BASELINE literal below was generated by running lambda_handler
against this mock state BEFORE the refactor.  After the refactor the handler
must produce the identical tuple sequence (Task 13 / REQ-5.3).
"""

from __future__ import annotations

from datetime import datetime, timezone
from unittest.mock import MagicMock, patch

import pytest

from .support import finserv_app as app


# ===========================================================================
# Account-state fixture helpers
# ===========================================================================

# ---- Lambda functions -------------------------------------------------------
# Two agent functions:  one WITH reserved concurrency (→ PASS in FS-09),
#                       one validate/output function (→ PASS in FS-55, affects FS-58)
# A "schema-validator" function is added so FS-58 finds it (ADVISORY row with count)
_LAMBDA_FUNCTIONS = [
    {"FunctionName": "my-bedrock-agent-handler"},
    {"FunctionName": "my-output-validate-fn"},
    {"FunctionName": "my-schema-validator-fn"},
]

# ---- Guardrails -------------------------------------------------------------
# One guardrail with full configuration (→ PASS paths across FS-27a/28/36/38/45/47/50/51/59)
_GUARDRAIL_SUMMARY = {"id": "gr-abc123", "name": "FinServGuardrail"}

_GUARDRAIL_DETAIL = {
    # topic policy with topics → FS-28 PASS (CLASSIC tier advisory),
    #                             FS-59 PASS (CLASSIC tier advisory)
    "topicPolicy": {
        "topics": [{"name": "investment-advice", "type": "DENY"}],
        "tier": {"tierName": "CLASSIC"},
    },
    # content filters → FS-36 PASS
    "contentPolicy": {
        "filters": [
            {"type": "HATE", "inputStrength": "HIGH", "outputStrength": "HIGH"},
            {"type": "VIOLENCE", "inputStrength": "MEDIUM", "outputStrength": "MEDIUM"},
        ]
    },
    # word filters → FS-38 PASS
    "wordPolicy": {
        "words": [{"text": "fraud"}],
        "managedWordLists": [{"type": "PROFANITY"}],
    },
    # PII filters → FS-45 PASS
    "sensitiveInformationPolicy": {
        "piiEntities": [{"type": "US_SOCIAL_SECURITY_NUMBER", "action": "BLOCK"}]
    },
    # contextual grounding → FS-27a PASS; grounding threshold ≥ 0.7 → FS-47 PASS;
    # relevance-grounding → FS-50 PASS (single policy covers all three)
    "contextualGroundingPolicy": {
        "filters": [
            {"type": "GROUNDING", "threshold": 0.8},
            {"type": "RELEVANCE", "threshold": 0.8},
        ]
    },
    # topic allowlist (FS-51 checks prompt injection input validation via guardrails)
}

# ---- Knowledge Bases --------------------------------------------------------
# One KB, one data source with recent updatedAt → FS-31 PASS
# Data source backed by a versioned S3 bucket → FS-33 PASS
_NOW = datetime.now(timezone.utc)
_KB_SUMMARY = {"knowledgeBaseId": "kb-00001", "name": "FinServKB"}

_KB_DATA_SOURCE_SUMMARY = {
    "dataSourceId": "ds-00001",
    "name": "FinServDS",
    "updatedAt": _NOW,  # fresh → FS-31 PASS
}

_KB_DATA_SOURCE_DETAIL = {
    "dataSource": {
        "dataSourceConfiguration": {
            "s3Configuration": {"bucketArn": "arn:aws:s3:::my-kb-datasource-bucket"}
        }
    }
}

# ---- S3 buckets -------------------------------------------------------------
# Two buckets within one page (≤ 1 page constraint).
# "my-training-dataset-bucket": versioned → FS-21 PASS
# "my-bedrock-kb-bucket":       tagged with data-classification → FS-46 PASS
# "my-kb-datasource-bucket":    versioned (for FS-33 data-source check above)
_S3_BUCKETS = [
    {"Name": "my-training-dataset-bucket"},
    {"Name": "my-bedrock-kb-bucket"},
    {"Name": "my-kb-datasource-bucket"},
]

# ---- WAFv2 Web ACLs ---------------------------------------------------------
# Two ACLs, both with AWSManagedRulesSQLiRuleSet + AWSManagedRulesCommonRuleSet +
# body-size constraints → FS-53 PASS, FS-56 PASS, FS-68 PASS; FS-01 PASS.
# Constraint: ≤ 100 ACLs.
_ACL_SUMMARIES = [
    {"Name": "FinServACL1", "Id": "acl-id-001", "ARN": "arn:aws:wafv2:::acl-id-001"},
    {"Name": "FinServACL2", "Id": "acl-id-002", "ARN": "arn:aws:wafv2:::acl-id-002"},
]

_ACL_DETAIL_TEMPLATE = {
    "Name": "FinServACL",
    "Id": "acl-id-xxx",
    "Rules": [
        {
            "Name": "SQLi",
            "Statement": {
                "ManagedRuleGroupStatement": {"Name": "AWSManagedRulesSQLiRuleSet"}
            },
        },
        {
            "Name": "Common",
            "Statement": {
                "ManagedRuleGroupStatement": {"Name": "AWSManagedRulesCommonRuleSet"}
            },
        },
        {
            "Name": "KnownBadInputs",
            "Statement": {
                "ManagedRuleGroupStatement": {
                    "Name": "AWSManagedRulesKnownBadInputsRuleSet"
                }
            },
        },
        {
            "Name": "SizeConstraint",
            "Statement": {
                "SizeConstraintStatement": {
                    "FieldToMatch": {"Body": {}},
                    "ComparisonOperator": "LE",
                    "Size": 8192,
                    "TextTransformations": [{"Priority": 0, "Type": "NONE"}],
                }
            },
        },
    ],
}


def _acl_detail(name: str, acl_id: str) -> dict:
    """Return a get_web_acl-style response for the given name/id."""
    detail = dict(_ACL_DETAIL_TEMPLATE)
    detail["Name"] = name
    detail["Id"] = acl_id
    return {"WebACL": detail}


# ===========================================================================
# Mock builder
# ===========================================================================


def _build_mock_client(
    lambda_functions=None,
    guardrail_summaries=None,
    guardrail_detail=None,
    kb_summaries=None,
    kb_data_source_summaries=None,
    kb_data_source_detail=None,
    s3_buckets=None,
    acl_summaries=None,
    acl_detail_fn=None,
):
    """Return a boto3.client side-effect that satisfies every AWS call made
    by lambda_handler for the supplied account state.

    Non-inventory calls (shield, sts, apigw, cloudwatch, etc.) return minimal
    valid responses so those non-inventory checks produce deterministic output.
    """
    if lambda_functions is None:
        lambda_functions = _LAMBDA_FUNCTIONS
    if guardrail_summaries is None:
        guardrail_summaries = [_GUARDRAIL_SUMMARY]
    if guardrail_detail is None:
        guardrail_detail = _GUARDRAIL_DETAIL
    if kb_summaries is None:
        kb_summaries = [_KB_SUMMARY]
    if kb_data_source_summaries is None:
        kb_data_source_summaries = [_KB_DATA_SOURCE_SUMMARY]
    if kb_data_source_detail is None:
        kb_data_source_detail = _KB_DATA_SOURCE_DETAIL
    if s3_buckets is None:
        s3_buckets = _S3_BUCKETS
    if acl_summaries is None:
        acl_summaries = _ACL_SUMMARIES
    if acl_detail_fn is None:
        acl_detail_fn = lambda name, acl_id: _acl_detail(name, acl_id)  # noqa: E731

    def side_effect(service, **kwargs):  # noqa: C901  (complexity OK for test helper)
        c = MagicMock()

        # ------------------------------------------------------------------ #
        # wafv2
        # ------------------------------------------------------------------ #
        if service == "wafv2":
            c.list_web_acls.return_value = {"WebACLs": acl_summaries}

            def get_web_acl(Name, Scope, Id, **kw):
                return acl_detail_fn(Name, Id)

            c.get_web_acl.side_effect = get_web_acl
            return c

        # ------------------------------------------------------------------ #
        # shield
        # ------------------------------------------------------------------ #
        if service == "shield":
            c.describe_subscription.return_value = {}  # shield advanced active
            return c

        # ------------------------------------------------------------------ #
        # lambda
        # ------------------------------------------------------------------ #
        if service == "lambda":
            c.list_functions.return_value = {
                "Functions": lambda_functions
                # No NextMarker → single page
            }

            def get_function_concurrency(FunctionName, **kw):
                # agent function has concurrency set
                if "agent" in FunctionName.lower():
                    return {"ReservedConcurrentExecutions": 5}
                return {}

            c.get_function_concurrency.side_effect = get_function_concurrency
            return c

        # ------------------------------------------------------------------ #
        # bedrock  (guardrails)
        # ------------------------------------------------------------------ #
        if service == "bedrock":
            c.list_guardrails.return_value = {
                "guardrails": guardrail_summaries
                # No nextToken → single page
            }
            c.get_guardrail.return_value = guardrail_detail

            # Non-inventory calls for other bedrock checks
            c.list_foundation_models.return_value = {
                "modelSummaries": [
                    {
                        "modelId": "anthropic.claude-3-sonnet-20240229-v1:0",
                        "modelLifecycle": {"status": "ACTIVE"},
                    }
                ]
            }
            c.list_custom_models.return_value = {"modelSummaries": []}
            c.list_model_cards.return_value = {"ModelCardSummaries": []}
            c.list_evaluation_jobs.return_value = {"jobSummaries": []}
            c.get_macie_session.side_effect = Exception("macie not enabled")
            c.list_automated_reasoning_policies.return_value = {
                "automatedReasoningPolicySummaries": []
            }
            return c

        # ------------------------------------------------------------------ #
        # bedrock-agent  (knowledge bases + data sources)
        # ------------------------------------------------------------------ #
        if service == "bedrock-agent":
            # The collector calls list_knowledge_bases directly via _paginate
            # (not via get_paginator).  We set up both the direct-call return
            # value AND the paginator so any remaining checks that still use
            # get_paginator also work.

            kb_paginator = MagicMock()
            kb_paginator.paginate.return_value = [
                {"knowledgeBaseSummaries": kb_summaries}
            ]

            def get_paginator(op):
                if op == "list_knowledge_bases":
                    return kb_paginator
                pag = MagicMock()
                pag.paginate.return_value = [{}]
                return pag

            c.get_paginator.side_effect = get_paginator

            # Direct method call used by _paginate inside collect_resource_inventory
            c.list_knowledge_bases.return_value = {
                "knowledgeBaseSummaries": kb_summaries
                # No nextToken → single page
            }

            # list_data_sources called via _paginate (which uses the direct method)
            c.list_data_sources.return_value = {
                "dataSourceSummaries": kb_data_source_summaries
            }

            # get_data_source for FS-33 / FS-65
            c.get_data_source.return_value = kb_data_source_detail

            # list_agents (for FS-07)
            c.list_agents.return_value = {"agentSummaries": []}
            return c

        # ------------------------------------------------------------------ #
        # s3
        # ------------------------------------------------------------------ #
        if service == "s3":
            c.list_buckets.return_value = {
                "Buckets": s3_buckets
                # No ContinuationToken → single page
            }

            def get_bucket_versioning(Bucket, **kw):
                # All buckets have versioning enabled → FS-21 PASS, FS-33 PASS
                return {"Status": "Enabled"}

            c.get_bucket_versioning.side_effect = get_bucket_versioning

            def get_bucket_tagging(Bucket, **kw):
                # All buckets have classification tag → FS-46 PASS
                return {
                    "TagSet": [{"Key": "data-classification", "Value": "Confidential"}]
                }

            c.get_bucket_tagging.side_effect = get_bucket_tagging

            # Bucket notification config for FS-65
            def get_bucket_notification_configuration(Bucket, **kw):
                return {
                    "EventBridgeConfiguration": {}  # event notifications present
                }

            c.get_bucket_notification_configuration.side_effect = (
                get_bucket_notification_configuration
            )
            return c

        # ------------------------------------------------------------------ #
        # Non-inventory services — return minimal responses so checks complete
        # ------------------------------------------------------------------ #

        if service == "apigateway":
            c.get_usage_plans.return_value = {
                "items": [
                    {
                        "name": "default",
                        "throttle": {"rateLimit": 500, "burstLimit": 200},
                    }
                ]
            }
            c.get_rest_apis.return_value = {"items": []}
            return c

        if service == "ce":  # cost explorer
            c.get_anomaly_monitors.return_value = {
                "AnomalyMonitors": [
                    {
                        "MonitorType": "DIMENSIONAL",
                        "MonitorDimension": "SERVICE",
                        "MonitorSpecification": {},
                    }
                ]
            }
            return c

        if service == "cloudwatch":
            pag = MagicMock()
            pag.paginate.return_value = [
                {
                    "MetricAlarms": [
                        {
                            "AlarmName": "bedrock-throttle-alarm",
                            "Namespace": "AWS/Bedrock",
                            "MetricName": "InvocationThrottles",
                        }
                    ]
                }
            ]
            c.get_paginator.return_value = pag
            return c

        if service == "budgets":
            pag = MagicMock()
            pag.paginate.return_value = [
                {
                    "Budgets": [
                        {
                            "BudgetName": "bedrock-spend",
                            "CostFilters": {"Service": ["Amazon Bedrock"]},
                        }
                    ]
                }
            ]
            c.get_paginator.return_value = pag
            return c

        if service == "sts":
            c.get_caller_identity.return_value = {"Account": "123456789012"}
            return c

        if service == "service-quotas":
            applied_pag = MagicMock()
            applied_pag.paginate.return_value = [
                {
                    "Quotas": [
                        {
                            "QuotaName": "On-demand InvokeModel tokens per minute for anthropic.claude",
                            "QuotaCode": "L-TPMTEST",
                            "Value": 200000,
                        }
                    ]
                }
            ]
            defaults_pag = MagicMock()
            defaults_pag.paginate.return_value = [
                {"Quotas": [{"QuotaCode": "L-TPMTEST", "Value": 100000}]}
            ]

            def get_paginator(op):
                if op == "list_service_quotas":
                    return applied_pag
                if op == "list_aws_default_service_quotas":
                    return defaults_pag
                p = MagicMock()
                p.paginate.return_value = [{}]
                return p

            c.get_paginator.side_effect = get_paginator
            return c

        if service == "stepfunctions":
            c.list_state_machines.return_value = {"stateMachines": []}
            return c

        if service == "iam":
            c.list_policies.return_value = {"Policies": []}
            pag = MagicMock()
            pag.paginate.return_value = [{}]
            c.get_paginator.return_value = pag
            return c

        if service == "config":
            c.describe_config_rules.return_value = {"ConfigRules": []}
            return c

        if service == "ecr":
            c.describe_repositories.return_value = {"repositories": []}
            return c

        if service == "sagemaker":
            c.list_feature_groups.return_value = {"FeatureGroupSummaries": []}
            c.list_processing_jobs.return_value = {"ProcessingJobSummaries": []}
            c.list_models.return_value = {"Models": []}
            pag = MagicMock()
            pag.paginate.return_value = [{}]
            c.get_paginator.return_value = pag
            return c

        if service == "logs":
            c.list_log_groups.return_value = {"logGroups": []}
            pag = MagicMock()
            pag.paginate.return_value = [{"logGroups": []}]
            c.get_paginator.return_value = pag
            return c

        if service == "macie2":
            c.get_macie_session.side_effect = Exception("macie not enabled")
            return c

        if service == "opensearchserverless":
            c.list_security_policies.return_value = {"securityPolicySummaries": []}
            return c

        if service == "bedrock-agent-runtime":
            return c

        if service == "bedrock-runtime":
            return c

        if service == "events":
            c.list_rules.return_value = {"Rules": []}
            return c

        if service == "scheduler":
            c.list_schedules.return_value = {"Schedules": []}
            return c

        if service == "agentcore":
            c.list_agent_runtimes.return_value = {"agentRuntimes": []}
            return c

        if service == "organizations":
            c.list_policies.return_value = {"Policies": []}
            return c

        # Catch-all: return a generic mock for any other service
        pag = MagicMock()
        pag.paginate.return_value = [{}]
        c.get_paginator.return_value = pag
        return c

    return side_effect


# ===========================================================================
# Shared pytest fixture
# ===========================================================================


@pytest.fixture
def account_state_mock():
    """Full single-page account state mock covering all inventory-consuming checks."""
    return _build_mock_client()


@pytest.fixture
def lambda_event():
    return {"Execution": {"Name": "equivalence-test-001"}}


# ===========================================================================
# Helper: run lambda_handler and extract the frozen tuple sequence
# ===========================================================================


def _enum_val(v) -> str:
    """Return the .value of an enum, or the value unchanged if it's already a str."""
    return v.value if hasattr(v, "value") else str(v)


def _run_handler_and_extract_tuples(mock_client_side_effect, event):
    """Run lambda_handler with the given mock and return the ordered list of
    (check_id, finding_name, status, severity, compliance_frameworks) tuples.

    Enum fields (Status, Severity) are coerced to their .value strings so the
    frozen BASELINE literal uses plain str values, making it readable and
    portable across Python versions.
    """
    with (
        patch("finserv_app.boto3.client") as mock_client,
        patch("finserv_app.get_permissions_cache") as mock_cache,
        patch("finserv_app.write_to_s3") as mock_s3,
    ):
        mock_client.side_effect = mock_client_side_effect
        mock_cache.return_value = {"role_permissions": {}, "user_permissions": {}}
        mock_s3.return_value = "https://test-bucket.s3.amazonaws.com/finserv_security_report_equivalence-test-001.csv"

        result = app.lambda_handler(event, None)

    tuples = []
    for finding in result["body"]["findings"]:
        for row in finding.get("csv_data", []):
            tuples.append(
                (
                    row.get("Check_ID", ""),
                    row.get("Finding", ""),
                    _enum_val(row.get("Status", "")),
                    _enum_val(row.get("Severity", "")),
                    row.get("Compliance_Frameworks", ""),
                )
            )
    return tuples


# ===========================================================================
# FROZEN BASELINE
# ===========================================================================
# Generated by running lambda_handler against the account-state fixture above
# on the PRE-REFACTOR code.  After the refactor Task 13 asserts this literal
# is reproduced exactly (REQ-5.3).
#
# NOTE: This literal is intentionally left empty here and will be populated
# once by the _test_generate_baseline helper below (run once, paste output,
# then use BASELINE in the main assertion test).
# ===========================================================================


# fmt: off
BASELINE: list[tuple[str, str, str, str, str]] = [
    ('FS-01', 'AWS Shield Advanced Enabled', 'Passed', 'Low', 'FFIEC CAT | DORA Art.6'),
    ('FS-01', 'Regional WAF Web ACLs Present', 'Passed', 'Medium', 'FFIEC CAT | DORA Art.6'),
    ('FS-02', 'API Gateway Rate Limiting Configured', 'Passed', 'Medium', 'FFIEC CAT | DORA Art.6 | PCI-DSS 12.3.2'),
    ('FS-03', 'Bedrock Token Quotas Customized', 'Passed', 'Medium', 'FFIEC CAT | SR 11-7'),
    ('FS-04', 'Cost Anomaly Detection Configured', 'Passed', 'Medium', 'FFIEC CAT | SR 11-7'),
    ('FS-05', 'Bedrock CloudWatch Alarms Present', 'Passed', 'Medium', 'FFIEC CAT | DORA Art.6'),
    ('FS-06', 'AI/ML Service Budgets Configured', 'Passed', 'Medium', 'FFIEC CAT | SR 11-7'),
    ('FS-07', 'Agent Action Boundary Check', 'N/A', 'Informational', 'SR 11-7 | FFIEC CAT'),
    ('FS-08', 'AgentCore Policy Engine Configured', 'Passed', 'High', 'SR 11-7 | MAS TRM 9.1'),
    ('FS-09', 'Agent Lambda Concurrency Limits Present', 'Passed', 'Medium', 'FFIEC CAT | SR 11-7'),
    ('FS-10', 'Human-in-the-Loop Check \u2014 No Agent Workflows Found', 'N/A', 'Informational', 'SR 11-7 | FFIEC CAT | MAS TRM 9.2'),
    ('FS-11', 'No Agent Rate Alarms Found', 'Failed', 'Medium', 'FFIEC CAT | DORA Art.6'),
    ('FS-12', 'No Bedrock-Scoped SCPs Found', 'Failed', 'High', 'SR 11-7 | FFIEC CAT | ISO 27001 A.15.2'),
    ('FS-13', 'Model Provenance Tags Present', 'Passed', 'Medium', 'SR 11-7 | ISO 27001 A.12.5 | FFIEC CAT'),
    ('FS-14', 'No Model Governance Config Rules Found', 'Failed', 'Medium', 'SR 11-7 | FFIEC CAT | ISO 27001 A.15.1'),
    ('FS-15', 'No Bedrock Evaluation Jobs Found', 'Failed', 'Medium', 'SR 11-7 | FFIEC CAT | MAS TRM 9.3'),
    ('FS-16', 'No ECR Repositories Found', 'N/A', 'Informational', 'ISO 27001 A.12.6 | FFIEC CAT | DORA Art.6'),
    ('FS-20', 'No SageMaker Feature Groups Found', 'N/A', 'Informational', 'SR 11-7 | FFIEC CAT'),
    ('FS-21', 'Training Data Buckets Have Versioning', 'Passed', 'High', 'SR 11-7 | ISO 27001 A.12.3 | FFIEC CAT'),
    ('FS-22', 'Knowledge Base IAM Permissions Look Appropriate', 'Passed', 'High', 'NYDFS 500 | FFIEC CAT | PCI-DSS 12.3.2'),
    ('FS-24', 'ADVISORY: Knowledge Base Metadata Filtering \u2014 Manual Review Required', 'N/A', 'Informational', 'NYDFS 500 | FFIEC CAT | PCI-DSS 12.3.2'),
    ('FS-25', 'No OpenSearch Serverless Encryption Policies', 'N/A', 'Informational', 'NYDFS 500 | PCI-DSS 3.5 | FFIEC CAT'),
    ('FS-26', 'No OpenSearch Serverless Network Policies', 'Failed', 'High', 'NYDFS 500 | FFIEC CAT | PCI-DSS 1.3'),
    ('FS-27', 'Contextual Grounding Enabled on Guardrails', 'Passed', 'High', 'SR 11-7 | FFIEC CAT | MAS TRM 9.2'),
    ('FS-27', 'No Automated Reasoning Policies Found', 'Failed', 'Medium', 'SR 11-7 | FFIEC CAT | MAS TRM 9.2'),
    ('FS-28', 'Denied Topics Configured on CLASSIC Tier', 'Passed', 'High', 'SR 11-7 | FFIEC CAT | NYDFS 500 | MAS TRM 9.2'),
    ('FS-29', 'ADVISORY: Compliance Disclaimer \u2014 Manual Review Required', 'N/A', 'Informational', 'SR 11-7 | FFIEC CAT | NYDFS 500 | MAS TRM 9.2'),
    ('FS-30', 'ADVISORY: Compliance Dataset Coverage \u2014 Manual Review Required', 'N/A', 'Informational', 'SR 11-7 | FFIEC CAT | NYDFS 500'),
    ('FS-31', 'Knowledge Base Data Sources Recently Synced', 'Passed', 'Medium', 'SR 11-7 | FFIEC CAT'),
    ('FS-32', 'ADVISORY: Source Attribution \u2014 Manual Review Required', 'N/A', 'Informational', 'SR 11-7 | FFIEC CAT | MAS TRM 9.2'),
    ('FS-33', 'KB Data Source Buckets Have Versioning', 'Passed', 'Medium', 'SR 11-7 | FFIEC CAT | ISO 27001 A.12'),
    ('FS-34', 'Foundation Models Are Current', 'Passed', 'Medium', 'SR 11-7 | FFIEC CAT'),
    ('FS-35', 'ADVISORY: Harmful-Content Test Coverage \u2014 Manual Review Required', 'N/A', 'Informational', 'SR 11-7 | FFIEC CAT'),
    ('FS-36', 'Guardrail Content Filters on CLASSIC Tier', 'Passed', 'High', 'SR 11-7 | FFIEC CAT'),
    ('FS-37', 'ADVISORY: User Feedback Mechanism \u2014 Manual Review Required', 'N/A', 'Informational', 'SR 11-7 | FFIEC CAT | MAS TRM 9.2'),
    ('FS-38', 'Guardrail Word Filters Configured', 'Passed', 'Medium', 'SR 11-7 | FFIEC CAT'),
    ('FS-39', 'No SageMaker Clarify Bias Monitoring', 'Failed', 'High', 'SR 11-7 | FFIEC CAT | ECOA/Fair Housing'),
    ('FS-40', 'ADVISORY: Bias Dataset Coverage \u2014 Manual Review Required', 'N/A', 'Informational', 'SR 11-7 | FFIEC CAT | ECOA/Fair Housing'),
    ('FS-41', 'No SageMaker Clarify Explainability Monitoring', 'Failed', 'High', 'SR 11-7 | FFIEC CAT'),
    ('FS-42', 'No SageMaker Model Cards Found', 'Failed', 'Medium', 'SR 11-7 | FFIEC CAT'),
    ('FS-43', 'CloudWatch Logs Data Protection Policies Present', 'Passed', 'High', 'NYDFS 500 | FFIEC CAT | PCI-DSS'),
    ('FS-44', 'COULD NOT ASSESS: Amazon Macie PII Scanning Check', 'N/A', 'Low', 'NYDFS 500 | FFIEC CAT | PCI-DSS'),
    ('FS-45', 'Guardrail PII Filters Configured', 'Passed', 'High', 'NYDFS 500 | FFIEC CAT | PCI-DSS'),
    ('FS-46', 'AI/ML Buckets Have Classification Tags', 'Passed', 'Medium', 'NYDFS 500 | FFIEC CAT | ISO 27001 A.12 | PCI-DSS'),
    ('FS-47', 'Guardrail Grounding Thresholds Appropriate', 'Passed', 'High', 'SR 11-7 | FFIEC CAT'),
    ('FS-48', 'No Active Knowledge Bases for RAG', 'Failed', 'Medium', 'SR 11-7 | FFIEC CAT'),
    ('FS-49', 'ADVISORY: Hallucination Disclaimer \u2014 Manual Review Required', 'N/A', 'Informational', 'SR 11-7 | FFIEC CAT | MAS TRM 9.2'),
    ('FS-50', 'Relevance Grounding Filters Present', 'Passed', 'Medium', 'SR 11-7 | FFIEC CAT'),
    ('FS-51', 'No Guardrails With Prompt Attack Filters', 'Failed', 'High', 'NYDFS 500 | FFIEC CAT | OWASP LLM Top 10'),
    ('FS-52', 'Bedrock Lambda Functions on Current Runtimes', 'Passed', 'Medium', 'NYDFS 500 | FFIEC CAT | ISO 27001 A.12 | OWASP LLM Top 10'),
    ('FS-53', 'WAF Injection Protection Rules Present', 'Passed', 'High', 'NYDFS 500 | PCI-DSS | FFIEC CAT | OWASP LLM Top 10'),
    ('FS-54', 'ADVISORY: Penetration Testing \u2014 Manual Review Required', 'N/A', 'Informational', 'NYDFS 500 | FFIEC CAT | OWASP LLM Top 10'),
    ('FS-55', 'Output Validation Functions Present', 'Passed', 'Medium', 'FFIEC CAT | OWASP LLM Top 10'),
    ('FS-56', 'XSS Prevention Common Rule Set Present', 'Passed', 'Medium', 'NYDFS 500 | PCI-DSS | OWASP LLM Top 10'),
    ('FS-57', 'ADVISORY: Output Encoding \u2014 Manual Review Required', 'N/A', 'Informational', 'NYDFS 500.06 | FFIEC CAT | OWASP LLM Top 10'),
    ('FS-58', 'ADVISORY: Output Schema Validation \u2014 Manual Review Required', 'N/A', 'Informational', 'FFIEC CAT | OWASP LLM Top 10'),
    ('FS-59', 'Topic Restrictions Configured on CLASSIC Tier', 'Passed', 'Medium', 'SR 11-7 | FFIEC CAT'),
    ('FS-60', 'ADVISORY: Contextual Grounding for Off-Topic Prevention', 'N/A', 'Informational', 'SR 11-7 | FFIEC CAT'),
    ('FS-61', 'No Automated KB Sync Schedules Detected', 'Failed', 'Medium', 'SR 11-7 | FFIEC CAT'),
    ('FS-62', 'ADVISORY: Data Currency Disclaimer \u2014 Manual Review Required', 'N/A', 'Informational', 'SR 11-7 | FFIEC CAT | MAS TRM 9.2'),
    ('FS-63', 'Foundation Model Lifecycle Management', 'Passed', 'Medium', 'SR 11-7 | FFIEC CAT | ISO 27001 A.12'),
    ('FS-65', 'KB Data Source Buckets Missing S3 Event Notifications', 'Failed', 'Medium', 'FFIEC CAT | DORA Art.6 | ISO 27001 A.12'),
    ('FS-66', 'AgentCore End-User Identity Propagation Configured', 'Passed', 'High', 'NYDFS 500 | SR 11-7 | MAS TRM 9 | PCI-DSS'),
    ('FS-67', 'Agent Action-Group Lambdas May Lack Transaction Thresholds', 'Failed', 'High', 'SR 11-7 | FFIEC CAT | MAS TRM 9 | PCI-DSS'),
    ('FS-68', 'API Gateway Request Body Size Limits Configured', 'Passed', 'Medium', 'DORA Art.6 | FFIEC CAT | PCI-DSS | OWASP LLM Top 10'),
    ('FS-69', 'Prompt Input Validation Functions Present', 'Passed', 'Medium', 'NYDFS 500 | FFIEC CAT | OWASP LLM Top 10'),
]
# fmt: on


# ===========================================================================
# REQ-5.4: Documented permitted deltas for multi-page account states
# ===========================================================================
#
# The BASELINE above was captured against a SINGLE-PAGE account state
# (≤100 WAFv2 REGIONAL Web ACLs, ≤1 page of S3 buckets).  For that state
# the post-refactor handler output MUST be byte-for-byte identical to BASELINE
# (REQ-5.3 / test_handler_output_matches_frozen_baseline).
#
# For multi-page account states, REQ-5.4 permits EXACTLY TWO classes of
# finding-set changes — both attributable to pagination-correctness fixes:
#
# PERMITTED DELTA 1 — WAFv2 Web ACLs (REQ-2.2):
#   Pre-refactor: wafv2.list_web_acls(Scope="REGIONAL") was called UNPAGINATED,
#   silently truncating at one page (≤100 ACLs).  Accounts with >100 REGIONAL
#   Web ACLs would have their ACL set incorrectly truncated.
#   Post-refactor: _paginate uses NextMarker/NextMarker token convention, so
#   ALL ACLs are returned.  Any finding rows attributable to ACLs beyond page 1
#   (e.g., FS-01, FS-53, FS-56, FS-68) that were previously invisible MAY now
#   appear.  Existing rows for ACLs within page 1 remain identical.
#
# PERMITTED DELTA 2 — S3 buckets (REQ-2.8):
#   Pre-refactor: s3.list_buckets() was called UNPAGINATED, silently truncating
#   at 1,000 buckets in standard accounts; outright FAILING (error → COULD_NOT_ASSESS)
#   for accounts whose bucket quota is above 10,000.
#   Post-refactor: _paginate uses ContinuationToken/ContinuationToken with
#   MaxBuckets=1000, so ALL buckets are enumerated and 10k-quota accounts succeed.
#   Finding rows for FS-21 and FS-46 may differ for buckets beyond page 1, and
#   accounts that previously produced COULD_NOT_ASSESS may now produce PASS/FAIL.
#
# ALL OTHER finding changes are defects (REQ-5.5) and must be corrected.
# ===========================================================================


# ===========================================================================
# Tests
# ===========================================================================


class TestGoldenEquivalenceBaseline:
    """Golden-equivalence oracle for the current (pre-refactor) lambda_handler.

    Requirements: REQ-5.1, REQ-5.3, REQ-5.6
    """

    def test_handler_produces_65_findings(self, account_state_mock, lambda_event):
        """Smoke test: all 65 registry entries produce at least one finding."""
        with (
            patch("finserv_app.boto3.client") as mock_client,
            patch("finserv_app.get_permissions_cache") as mock_cache,
            patch("finserv_app.write_to_s3") as mock_s3,
        ):
            mock_client.side_effect = account_state_mock
            mock_cache.return_value = {"role_permissions": {}, "user_permissions": {}}
            mock_s3.return_value = "https://test-bucket.s3.amazonaws.com/report.csv"

            result = app.lambda_handler(lambda_event, None)

        assert result["statusCode"] == 200
        findings = result["body"]["findings"]
        assert len(findings) == 65, f"Expected 65 registry entries; got {len(findings)}"

    def test_all_findings_have_rows(self, account_state_mock, lambda_event):
        """Every registry entry emits at least one CSV row (no silent drops)."""
        with (
            patch("finserv_app.boto3.client") as mock_client,
            patch("finserv_app.get_permissions_cache") as mock_cache,
            patch("finserv_app.write_to_s3") as mock_s3,
        ):
            mock_client.side_effect = account_state_mock
            mock_cache.return_value = {"role_permissions": {}, "user_permissions": {}}
            mock_s3.return_value = "https://test-bucket.s3.amazonaws.com/report.csv"

            result = app.lambda_handler(lambda_event, None)

        for finding in result["body"]["findings"]:
            assert finding.get("csv_data"), (
                f"Finding '{finding.get('check_name')}' produced no CSV rows"
            )

    def test_fixture_covers_pass_paths(self, account_state_mock, lambda_event):
        """The fixture exercises PASS paths for the inventory-consuming checks."""
        with (
            patch("finserv_app.boto3.client") as mock_client,
            patch("finserv_app.get_permissions_cache") as mock_cache,
            patch("finserv_app.write_to_s3") as mock_s3,
        ):
            mock_client.side_effect = account_state_mock
            mock_cache.return_value = {"role_permissions": {}, "user_permissions": {}}
            mock_s3.return_value = "https://test-bucket.s3.amazonaws.com/report.csv"

            result = app.lambda_handler(lambda_event, None)

        all_rows = [
            row for f in result["body"]["findings"] for row in f.get("csv_data", [])
        ]
        passed_ids = {r["Check_ID"] for r in all_rows if r.get("Status") == "Passed"}

        # These checks should produce PASS rows with our fixture
        expected_pass = {"FS-01", "FS-09", "FS-21", "FS-27", "FS-28", "FS-33", "FS-45"}
        for check_id in expected_pass:
            assert check_id in passed_ids, (
                f"Expected PASS for {check_id} but not found in {passed_ids}"
            )

    def test_fixture_covers_na_paths(self, account_state_mock, lambda_event):
        """The fixture exercises N/A paths (advisory checks emit Status='N/A')."""
        with (
            patch("finserv_app.boto3.client") as mock_client,
            patch("finserv_app.get_permissions_cache") as mock_cache,
            patch("finserv_app.write_to_s3") as mock_s3,
        ):
            mock_client.side_effect = account_state_mock
            mock_cache.return_value = {"role_permissions": {}, "user_permissions": {}}
            mock_s3.return_value = "https://test-bucket.s3.amazonaws.com/report.csv"

            result = app.lambda_handler(lambda_event, None)

        all_rows = [
            row for f in result["body"]["findings"] for row in f.get("csv_data", [])
        ]
        na_ids = {r["Check_ID"] for r in all_rows if r.get("Status") == "N/A"}

        # Advisory/N/A checks should appear
        expected_na = {"FS-24", "FS-29", "FS-30", "FS-32", "FS-54", "FS-57", "FS-60"}
        for check_id in expected_na:
            assert check_id in na_ids, (
                f"Expected N/A for {check_id} but not found in {na_ids}"
            )

    def test_fixture_covers_fail_paths(self, lambda_event):
        """The fixture exercises FAIL paths for select inventory-consuming checks."""
        # Use a variant fixture where guardrail has NO PII filters → FS-45 FAIL
        guardrail_without_pii = dict(_GUARDRAIL_DETAIL)
        guardrail_without_pii = {
            k: v
            for k, v in _GUARDRAIL_DETAIL.items()
            if k != "sensitiveInformationPolicy"
        }
        guardrail_without_pii["sensitiveInformationPolicy"] = {}

        fail_mock = _build_mock_client(guardrail_detail=guardrail_without_pii)

        with (
            patch("finserv_app.boto3.client") as mock_client,
            patch("finserv_app.get_permissions_cache") as mock_cache,
            patch("finserv_app.write_to_s3") as mock_s3,
        ):
            mock_client.side_effect = fail_mock
            mock_cache.return_value = {"role_permissions": {}, "user_permissions": {}}
            mock_s3.return_value = "https://test-bucket.s3.amazonaws.com/report.csv"

            result = app.lambda_handler(lambda_event, None)

        all_rows = [
            row for f in result["body"]["findings"] for row in f.get("csv_data", [])
        ]
        failed_ids = {r["Check_ID"] for r in all_rows if r.get("Status") == "Failed"}
        assert "FS-45" in failed_ids, (
            "Expected FS-45 FAIL when guardrail has no PII filters"
        )

    def test_baseline_tuple_count_is_stable(self, account_state_mock, lambda_event):
        """Capture the pre-refactor tuples and assert the count is deterministic.

        The frozen BASELINE literal is populated by test_capture_and_freeze_baseline
        below.  This test asserts the count (and therefore structure) is stable
        across runs, which is the prerequisite for freezing it as a literal.
        """
        t1 = _run_handler_and_extract_tuples(account_state_mock, lambda_event)
        t2 = _run_handler_and_extract_tuples(
            _build_mock_client(),
            lambda_event,  # fresh instance, same state
        )
        assert t1 == t2, (
            "lambda_handler is non-deterministic: two identical runs produced different tuples"
        )
        assert len(t1) > 0, "No tuples extracted — fixture may be broken"

    def test_handler_output_matches_frozen_baseline(
        self, account_state_mock, lambda_event
    ):
        """Golden-equivalence oracle: the handler output must equal BASELINE exactly.

        REQ-5.1, REQ-5.3, REQ-5.6 — This test is the live oracle that will remain
        green after the refactor in Tasks 2–15.  It asserts that:
          1. The (check_id, finding_name, status, severity, compliance_frameworks)
             tuples are identical to the pre-refactor frozen literal.
          2. Row ordering is preserved (CSV row ordering per REQ-5.6).
          3. The BASELINE covers ≤100 Web ACLs and ≤1 page of S3 buckets so it
             remains directly comparable after the pagination fix (REQ-5.3).
        """
        actual = _run_handler_and_extract_tuples(account_state_mock, lambda_event)
        assert actual == BASELINE, (
            f"Handler output differs from frozen BASELINE.\n"
            f"Expected {len(BASELINE)} tuples, got {len(actual)}.\n"
            f"First diff at index "
            + str(
                next(
                    (i for i, (a, b) in enumerate(zip(actual, BASELINE)) if a != b),
                    min(len(actual), len(BASELINE)),
                )
            )
            + "."
        )


class TestPermittedMultiPageDeltas:
    """Validates the two permitted finding-set changes for multi-page account states.

    REQ-5.4: findings may ONLY change for resources beyond page 1 of WAFv2 Web
    ACLs (>100 ACLs) or S3 buckets (>1 page / >10k quota).  All other rows
    must remain identical to the single-page BASELINE.

    These tests use two-page fixtures so we can verify:
      1. Rows attributable to page-1 resources are identical to BASELINE.
      2. Rows attributable to page-2+ resources appear (new, post-refactor only).
    """

    def test_wafv2_multi_page_page1_rows_unchanged(self, lambda_event):
        """REQ-5.4 WAFv2 delta: finding changes attributable ONLY to page-2+ ACLs are permitted.

        Scenario: page 1 = well-configured ACLs (same as BASELINE), page 2 = one ACL
        MISSING injection-protection rules.  Pre-refactor: that ACL was silently
        truncated so checks passed (BASELINE).  Post-refactor: the ACL is seen and
        checks correctly fail.

        This is the ONLY class of WAFv2 finding change REQ-5.4 permits.
        """
        # Extra ACL on page 2 — missing injection/XSS rules → FS-53, FS-56 should now FAIL
        extra_acl = {
            "Name": "BadACL",
            "Id": "acl-id-999",
            "ARN": "arn:aws:wafv2:::acl-id-999",
        }
        bad_acl_detail = {
            "WebACL": {
                "Name": "BadACL",
                "Id": "acl-id-999",
                "Rules": [],  # No managed rule groups — missing injection protection
            }
        }

        def mock_with_two_page_wafv2(service, **kwargs):
            c = _build_mock_client()(service, **kwargs)
            if service == "wafv2":
                c_waf = MagicMock()
                call_count = {"n": 0}

                def list_web_acls_two_pages(**kw):
                    call_count["n"] += 1
                    if call_count["n"] == 1:
                        return {"WebACLs": _ACL_SUMMARIES, "NextMarker": "page2token"}
                    return {"WebACLs": [extra_acl]}

                c_waf.list_web_acls.side_effect = list_web_acls_two_pages

                def get_web_acl(Name, Scope, Id, **kw):
                    if Id == "acl-id-999":
                        return bad_acl_detail
                    return _acl_detail(Name, Id)

                c_waf.get_web_acl.side_effect = get_web_acl
                return c_waf
            return c

        with (
            patch("finserv_app.boto3.client") as mock_client,
            patch("finserv_app.get_permissions_cache") as mock_cache,
            patch("finserv_app.write_to_s3"),
        ):
            mock_client.side_effect = mock_with_two_page_wafv2
            mock_cache.return_value = {"role_permissions": {}, "user_permissions": {}}
            result = app.lambda_handler(lambda_event, None)

        actual = []
        for finding in result["body"]["findings"]:
            for row in finding.get("csv_data", []):
                actual.append(
                    (
                        row.get("Check_ID", ""),
                        row.get("Finding", ""),
                        _enum_val(row.get("Status", "")),
                        _enum_val(row.get("Severity", "")),
                        row.get("Compliance_Frameworks", ""),
                    )
                )

        actual_by_id = {t[0]: t for t in actual}

        # REQ-5.4: WAFv2 checks (FS-53, FS-56) MUST now fail because the page-2 ACL
        # is missing injection/XSS rules.  This is the PERMITTED delta.
        assert actual_by_id.get("FS-53", ("", "", "", "", ""))[2] == "Failed", (
            "FS-53 must FAIL when a page-2 ACL has no injection-protection rules"
        )
        assert actual_by_id.get("FS-56", ("", "", "", "", ""))[2] == "Failed", (
            "FS-56 must FAIL when a page-2 ACL has no XSS rules"
        )

        # REQ-5.4: All non-WAFv2 check rows are UNCHANGED (no collateral damage)
        wafv2_check_ids = {"FS-01", "FS-53", "FS-56", "FS-68"}
        for row in BASELINE:
            check_id = row[0]
            if check_id in wafv2_check_ids:
                continue  # WAFv2 rows are the permitted delta — skip
            assert row in actual, (
                f"REQ-5.4 violation: non-WAFv2 BASELINE row {row!r} missing from output"
            )

    def test_s3_multi_page_page1_rows_unchanged(self, lambda_event):
        """REQ-5.4 S3 delta: page-1 bucket rows must be identical to BASELINE.

        Uses a two-page S3 fixture (page 1 = the fixture buckets, page 2 = one
        additional bucket).  Asserts that the page-1 bucket findings are identical
        to the single-page BASELINE.
        """
        extra_bucket = {"Name": "extra-ml-bucket-page2"}

        def mock_with_two_page_s3(service, **kwargs):
            c = _build_mock_client()(service, **kwargs)
            if service == "s3":
                c_s3 = MagicMock()
                call_count = {"n": 0}

                def list_buckets_two_pages(**kw):
                    call_count["n"] += 1
                    if call_count["n"] == 1:
                        return {
                            "Buckets": _S3_BUCKETS,
                            "ContinuationToken": "page2token",
                        }
                    return {"Buckets": [extra_bucket]}

                c_s3.list_buckets.side_effect = list_buckets_two_pages

                def get_bucket_versioning(Bucket, **kw):
                    return {"Status": "Enabled"}

                c_s3.get_bucket_versioning.side_effect = get_bucket_versioning

                def get_bucket_tagging(Bucket, **kw):
                    return {
                        "TagSet": [
                            {"Key": "data-classification", "Value": "Confidential"}
                        ]
                    }

                c_s3.get_bucket_tagging.side_effect = get_bucket_tagging

                def get_bucket_notification_configuration(Bucket, **kw):
                    return {"EventBridgeConfiguration": {}}

                c_s3.get_bucket_notification_configuration.side_effect = (
                    get_bucket_notification_configuration
                )
                return c_s3
            return c

        with (
            patch("finserv_app.boto3.client") as mock_client,
            patch("finserv_app.get_permissions_cache") as mock_cache,
            patch("finserv_app.write_to_s3"),
        ):
            mock_client.side_effect = mock_with_two_page_s3
            mock_cache.return_value = {"role_permissions": {}, "user_permissions": {}}
            result = app.lambda_handler(lambda_event, None)

        actual = []
        for finding in result["body"]["findings"]:
            for row in finding.get("csv_data", []):
                actual.append(
                    (
                        row.get("Check_ID", ""),
                        row.get("Finding", ""),
                        _enum_val(row.get("Status", "")),
                        _enum_val(row.get("Severity", "")),
                        row.get("Compliance_Frameworks", ""),
                    )
                )

        # All BASELINE rows must still appear — delta is ADDITIVE only for extra buckets
        for row in BASELINE:
            assert row in actual, (
                f"REQ-5.4 violation: BASELINE row {row!r} missing from multi-page S3 output"
            )

        # Must have at least as many rows as BASELINE (extra bucket may add rows)
        assert len(actual) >= len(BASELINE)


class TestCaptureAndFreezeBaseline:
    """Helper test that prints the frozen literal for copy/paste into BASELINE.

    Run once with: pytest tests/test_inventory_equivalence.py::TestCaptureAndFreezeBaseline -s
    Then copy the printed literal into the BASELINE constant above and delete this class
    (or keep it as a regeneration helper).
    """

    def test_print_baseline_literal(self, account_state_mock, lambda_event, capsys):
        """Print the BASELINE literal so it can be pasted into the BASELINE constant."""
        tuples = _run_handler_and_extract_tuples(account_state_mock, lambda_event)

        with capsys.disabled():
            print("\n\n# ===== PASTE INTO BASELINE CONSTANT =====")
            print("BASELINE: list[tuple[str, str, str, str, str]] = [")
            for t in tuples:
                # repr each element so special chars are safe
                row_repr = ", ".join(repr(x) for x in t)
                print(f"    ({row_repr}),")
            print("]")
            print("# ===== END BASELINE =====\n")

        # The test itself passes as long as tuples are produced
        assert len(tuples) > 0
